apiVersion: v1
kind: ServiceAccount
metadata:
  name: file-service
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "companyos.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.objectStorage.fileServiceRoleArn }}
    eks.amazonaws.com/role-arn: {{ .Values.objectStorage.fileServiceRoleArn | quote }}
    {{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: companyos-default
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "companyos.labels" . | nindent 4 }}
