//! OpenAPI 3.1 document for the CompanyOS Finance API (`/api/v1/finance/...`).

use axum::routing::get;
use axum::{Json, Router};
use utoipa::OpenApi;

use crate::handlers::{
    accounts, bank, credit_notes, customers, events, expenses, invoices, journals, payments,
    periods, policy, recurring, reports, webhooks,
};
use crate::state::AppState;
use crate::types::*;

#[derive(OpenApi)]
#[openapi(
    paths(
        customers::list_customers,
        customers::get_customer,
        invoices::list_invoices,
        invoices::create_invoice,
        invoices::get_invoice,
        invoices::update_invoice,
        invoices::issue_invoice,
        invoices::send_invoice,
        invoices::void_invoice,
        invoices::create_from_quote,
        payments::list_payments,
        payments::record_payment,
        payments::allocate_payment,
        credit_notes::create_credit_note,
        expenses::list_expenses,
        expenses::submit_expense,
        expenses::decide_expense,
        reports::report_summary,
        reports::trial_balance,
        reports::profit_and_loss,
        reports::balance_sheet,
        webhooks::stripe_webhook,
        recurring::create_recurring,
        recurring::run_due,
        events::apply_sales_event_handler,
        journals::post_journal_handler,
        journals::list_journals,
        journals::get_journal,
        accounts::list_accounts_tree,
        accounts::create_account,
        accounts::update_account,
        periods::list_periods,
        periods::create_period,
        periods::close_period,
        periods::reopen_period,
        periods::update_checklist,
        bank::list_bank_accounts,
        bank::create_bank_account,
        bank::import_statement,
        bank::auto_match_statement,
        bank::list_unmatched_lines,
        policy::get_expense_policy,
        policy::upsert_expense_policy,
        policy::create_mileage_expense,
        policy::create_per_diem_expense,
        policy::import_card_csv,
        policy::auto_match_cards,
        policy::create_reimbursement_batch,
        policy::decide_reimbursement,
    ),
    components(schemas(
        FinanceCustomerDto,
        FinanceCustomerListResponse,
        InvoiceLineDto,
        InvoiceDto,
        InvoiceListResponse,
        InvoiceLineInput,
        CreateInvoiceRequest,
        UpdateInvoiceRequest,
        IssueInvoiceRequest,
        QuoteLineSnapshot,
        CreateInvoiceFromQuoteRequest,
        PaymentDto,
        PaymentListResponse,
        RecordPaymentRequest,
        AllocatePaymentRequest,
        CreditNoteDto,
        CreditNoteListResponse,
        CreateCreditNoteRequest,
        ExpenseDto,
        ExpenseListResponse,
        SubmitExpenseRequest,
        DecideExpenseRequest,
        ReportSummaryDto,
        AgeingBucket,
        CategoryAmount,
        CashFlowPoint,
        StripeWebhookFixture,
        StripeWebhookData,
        StripePaymentObject,
        WebhookAck,
        RecurringInvoiceDto,
        RecurringListResponse,
        CreateRecurringRequest,
        RunDueResponse,
        ApplySalesEventRequest,
        ApplySalesEventResponse,
        ListQuery,
        JournalLineInput,
        PostJournalRequest,
        JournalEntryDto,
        JournalListResponse,
        JournalListQuery,
        LedgerAccountDto,
        LedgerAccountNode,
        LedgerAccountTreeResponse,
        CreateLedgerAccountRequest,
        UpdateLedgerAccountRequest,
        FiscalPeriodDto,
        FiscalPeriodListResponse,
        CreateFiscalPeriodRequest,
        ClosePeriodRequest,
        ReopenPeriodRequest,
        UpdateChecklistRequest,
        TrialBalanceRow,
        TrialBalanceResponse,
        ReportLine,
        ProfitAndLossResponse,
        BalanceSheetResponse,
        BankAccountDto,
        CreateBankAccountRequest,
        BankStatementDto,
        ImportStatementRequest,
        ImportStatementResponse,
        StatementLineDto,
        ReconcileRequest,
        ReconcileResponse,
        ReconciliationDto,
        CategoryLimitDto,
        CategoryLimitInput,
        ExpensePolicyDto,
        UpsertExpensePolicyRequest,
        MileageCalculateRequest,
        MileageCalculateResponse,
        PerDiemRequest,
        PerDiemResponse,
        CardTransactionDto,
        ImportCardCsvRequest,
        ImportCardResponse,
        MatchCardsResponse,
        ReimbursementBatchDto,
        CreateReimbursementBatchRequest,
        DecideReimbursementRequest,
    )),
    tags(
        (name = "finance-customers", description = "Projected finance customers"),
        (name = "finance-invoices", description = "Invoices: draft, issue, send, void"),
        (name = "finance-payments", description = "Payments and allocations"),
        (name = "finance-credit-notes", description = "Credit notes"),
        (name = "finance-expenses", description = "Expenses and approvals"),
        (name = "finance-reports", description = "Finance summary and accounting reports"),
        (name = "finance-webhooks", description = "Provider webhooks"),
        (name = "finance-recurring", description = "Recurring invoice templates"),
        (name = "finance-events", description = "In-process sales event apply"),
        (name = "finance-journals", description = "Balanced journal posting and list"),
        (name = "finance-accounts", description = "Chart of accounts"),
        (name = "finance-periods", description = "Fiscal periods open/close/reopen"),
        (name = "finance-bank", description = "Bank accounts, statements, reconciliation"),
        (name = "finance-policy", description = "Expense policy, cards, reimbursements"),
    ),
    info(
        title = "CompanyOS Finance API",
        version = "0.1.0",
        description = "Phase 1.5–2.4 — Finance: invoices, payments, expenses, payroll journals, CoA, periods, bank recon, expense policy."
    )
)]
pub struct ApiDoc;

pub fn router() -> Router<AppState> {
    Router::new().route(
        "/api/v1/finance/openapi.json",
        get(|| async { Json(ApiDoc::openapi()) }),
    )
}

/// Write the OpenAPI document as pretty JSON (used by `examples/export_openapi.rs`).
pub fn openapi_json() -> String {
    ApiDoc::openapi().to_pretty_json().expect("openapi json")
}
