//! OpenAPI 3.1 document for the CompanyOS CRM / Sales API (`/api/v1/sales/...`).

use axum::routing::get;
use axum::{Json, Router};
use utoipa::OpenApi;

use crate::handlers::{
    activities, contacts, contracts, customers, deals, imports, leads, orders, pipelines, products,
    quotes, reports, territories,
};
use crate::state::AppState;
use crate::types::*;

#[derive(OpenApi)]
#[openapi(
    paths(
        pipelines::list_pipelines,
        pipelines::default_board,
        customers::list_customers,
        customers::create_customer,
        customers::get_customer,
        customers::update_customer,
        customers::delete_customer,
        contacts::list_contacts,
        contacts::create_contact,
        contacts::update_contact,
        leads::list_leads,
        leads::create_lead,
        leads::get_lead,
        leads::update_lead,
        leads::qualify_lead,
        leads::disqualify_lead,
        leads::convert_lead,
        deals::list_deals,
        deals::create_deal,
        deals::get_deal,
        deals::update_deal,
        deals::win_deal,
        deals::lose_deal,
        activities::list_activities,
        activities::create_activity,
        products::list_products,
        products::create_product,
        products::update_product,
        quotes::list_quotes,
        quotes::create_quote,
        quotes::get_quote,
        quotes::update_quote,
        quotes::send_quote,
        quotes::accept_quote,
        quotes::reject_quote,
        quotes::invoice_action,
        orders::list_orders,
        orders::create_order,
        orders::get_order,
        orders::update_order_status,
        orders::order_from_quote,
        orders::order_from_deal,
        contracts::list_contracts,
        contracts::create_contract,
        contracts::get_contract,
        contracts::update_contract,
        contracts::publish_contract,
        contracts::list_renewals,
        territories::list_territories,
        territories::create_territory,
        territories::get_territory,
        territories::update_territory,
        territories::assign_territory,
        imports::preview_customers,
        imports::confirm_customers,
        reports::report_summary,
    ),
    components(schemas(
        PipelineDto,
        PipelineListResponse,
        StageDto,
        BoardStage,
        BoardResponse,
        CustomerDto,
        CustomerListResponse,
        CreateCustomerRequest,
        UpdateCustomerRequest,
        CreateCustomerResponse,
        ContactDto,
        ContactListResponse,
        CreateContactRequest,
        UpdateContactRequest,
        LeadDto,
        LeadListResponse,
        CreateLeadRequest,
        UpdateLeadRequest,
        DisqualifyLeadRequest,
        ConvertLeadRequest,
        ConvertLeadResponse,
        DuplicateMatch,
        DuplicateCheckResponse,
        DealDto,
        DealListResponse,
        CreateDealRequest,
        UpdateDealRequest,
        WinDealRequest,
        LoseDealRequest,
        ActivityDto,
        ActivityListResponse,
        CreateActivityRequest,
        ProductDto,
        ProductListResponse,
        CreateProductRequest,
        UpdateProductRequest,
        QuoteLineDto,
        QuoteDto,
        QuoteListResponse,
        CreateQuoteLineRequest,
        CreateQuoteRequest,
        UpdateQuoteRequest,
        RejectQuoteRequest,
        InvoiceActionResponse,
        OrderLineDto,
        OrderDto,
        OrderListResponse,
        CreateOrderLineRequest,
        CreateOrderRequest,
        UpdateOrderStatusRequest,
        OrderFromQuoteRequest,
        OrderFromDealRequest,
        ContractDto,
        ContractListResponse,
        CreateContractRequest,
        UpdateContractRequest,
        RenewalPipelineResponse,
        TerritoryDto,
        TerritoryListResponse,
        CreateTerritoryRequest,
        UpdateTerritoryRequest,
        AssignTerritoryRequest,
        TerritoryAssignmentDto,
        ImportPreviewRequest,
        ImportRowPreview,
        ImportPreviewResponse,
        ImportRowInput,
        ImportConfirmRequest,
        ImportConfirmResponse,
        StageSummary,
        WinRateSummary,
        ActivityVolumeItem,
        WeightedForecast,
        ReportSummaryResponse,
        MessageResponse,
    )),
    tags(
        (name = "sales-pipelines", description = "Pipelines, stages, and the kanban board"),
        (name = "sales-customers", description = "Customer accounts"),
        (name = "sales-contacts", description = "Contacts on customer accounts"),
        (name = "sales-leads", description = "Lead capture, qualification, and conversion"),
        (name = "sales-deals", description = "Deals / opportunities"),
        (name = "sales-activities", description = "Calls, meetings, emails, and notes"),
        (name = "sales-products", description = "Quotable product catalogue"),
        (name = "sales-quotes", description = "Quote drafting, versioning, and acceptance"),
        (name = "sales-orders", description = "Sales orders from quotes and won deals"),
        (name = "sales-contracts", description = "Customer contracts, publish, and renewals"),
        (name = "sales-territories", description = "Sales territories and assignments"),
        (name = "sales-imports", description = "CSV customer import"),
        (name = "sales-reports", description = "Pipeline / win-rate / forecast reports"),
    ),
    info(
        title = "CompanyOS CRM API",
        version = "0.1.0",
        description = "Phase 1.4 + 3.5 — Sales bounded context: customers, leads, deals, quotes, orders, contracts, territories, and reporting."
    )
)]
pub struct ApiDoc;

pub fn router() -> Router<AppState> {
    Router::new().route(
        "/api/v1/sales/openapi.json",
        get(|| async { Json(ApiDoc::openapi()) }),
    )
}

/// Write the OpenAPI document as pretty JSON (used by `examples/export_openapi.rs`).
pub fn openapi_json() -> String {
    ApiDoc::openapi().to_pretty_json().expect("openapi json")
}
